// <auto-generated />
namespace Avia8r.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migratingAvia8r : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migratingAvia8r));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200005548_migratingAvia8r"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
